### ISSUE TITLE
pure css slideshow

### ISSUE THREAD

**Issue by ivanberry** [ivanberry/css3-TTA#1]
### 基本知识点
1. `transition-property`
2. `transition-duration`
3. `transition-timing-function`
4. `transition-delay`

`transition`：状态见的切换，需要一个“开关”出发（hover)

``` css
a {
    color: #000;
    transition: color .7s ease-in .3s;
}

a:hover {
color: #fff;
} 
```
### CSS3: animation

[基本知识点](https://www.processon.com/view/5695a67ee4b0cfc27365b362)
1. `animation-delay`: 动画开启的时间
2. `animation-direction`：
3. `animation-duration`：持续时间
4. `animation-iteration-count`：动画完成次数
5. `animation-name`：动画帧名称（调用的对象名）
6. `animation-play-state`：动画状态
7. `animation-timing-function`：动画执行的“规则”，有点像PPT中的各种特效
8. `animation-fill-mode`：
9. `@keyframes`：帧定义

知道基本的知识后，就要了解轮播的基本原理，如图

![slide](https://media-mediatemple.netdna-ssl.com/wp-content/uploads/2012/03/sketch-1.jpg)

需要用的动画：改变top属性z-index还有opacity
